---

- name: Generate CSRs
  command: >-
    easyrsa
      {{ '--passout=pass:' + item.pass if item.pass | default(None) else '' }}
      gen-req
      {{ item.name }}
      {{ 'nopass' if not item.pass | default(None) else '' }}
  args:
    creates: "{{ easyrsa_pki_dir }}/issued/{{ item.name }}.crt"
  environment:
    EASYRSA_REQ_CN: "{{ item.cn | d(item.name, true) }}"
  loop: "{{ easyrsa_servers + easyrsa_clients }}"
  no_log: "{{ lookup('ansible.builtin.env', 'MOLECULE_FILE') is falsy }}"
