---

- name: Renew certificates
  command: easyrsa renew "{{ _easyrsa__cert.name }}"
  loop: "{{ easyrsa_renew }}"
  loop_control:
    loop_var: _easyrsa__cert
  register: _result
  failed_when:
    - _result is failed
    - _result is not search('Certificate expires in more than 30 days')
  changed_when: _result is not failed
