---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint --config-file molecule/default/yamllint.yml .
  ansible-lint -c molecule/default/ansible-lint.yml .
platforms:
  - name: ${MOLECULE_INSTANCE_NAME}
    image: ${MOLECULE_DOCKER_IMAGE}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    vvv: true
verifier:
  name: ansible
