---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - fixes
  pull_request:
    branches:
      - master
      - fixes

  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - distro: ubuntu
            version: 1804

    env:
      # IMAGE: jrei/systemd-${{ matrix.distro.distro }}:${{ matrix.distro.version }}
      # IMAGE: geerlingguy-${{ matrix.distro.distro }}${{ matrix.distro.version }}-ansible
      # INSTANCE: ${{ matrix.distro.distro }}-${{ matrix.distro.version }}
      IMAGE: geerlingguy-ubuntu1804-ansible
      INSTANCE: ubuntu1804
      DRIVER: docker

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      # - name: Install ansible
        # run: pip install -U ansible

      - name: Install molecule
        run: pip3 install ansible-lint molecule molecule-${{ env.DRIVER }} ${{ env.DRIVER }}

      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ env.IMAGE }}
          MOLECULE_INSTANCE_NAME: ${{ env.INSTANCE }}
